// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg2H8nrlHUL2efNDIvpEdZiGC9q1tzEy4',
    appId: '1:819485470108:android:01cb086d1ff97a307e2c59',
    messagingSenderId: '819485470108',
    projectId: 'mindflow-56836',
    storageBucket: 'mindflow-56836.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZz96cfFMI6abBlc1t8JXhrHVXn7NV8Js',
    appId: '1:819485470108:ios:cbf4b084bfea94097e2c59',
    messagingSenderId: '819485470108',
    projectId: 'mindflow-56836',
    storageBucket: 'mindflow-56836.firebasestorage.app',
    iosBundleId: 'com.example.mindflow',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZz96cfFMI6abBlc1t8JXhrHVXn7NV8Js',
    appId: '1:819485470108:ios:cbf4b084bfea94097e2c59',
    messagingSenderId: '819485470108',
    projectId: 'mindflow-56836',
    storageBucket: 'mindflow-56836.firebasestorage.app',
    iosBundleId: 'com.example.mindflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3XktQ0Gv-drYlKWdF7Q4BW74eglFKwFQ',
    appId: '1:819485470108:web:c7f264d1f4c08bf47e2c59',
    messagingSenderId: '819485470108',
    projectId: 'mindflow-56836',
    authDomain: 'mindflow-56836.firebaseapp.com',
    storageBucket: 'mindflow-56836.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3XktQ0Gv-drYlKWdF7Q4BW74eglFKwFQ',
    appId: '1:819485470108:web:c7f264d1f4c08bf47e2c59',
    messagingSenderId: '819485470108',
    projectId: 'mindflow-56836',
    authDomain: 'mindflow-56836.firebaseapp.com',
    storageBucket: 'mindflow-56836.firebasestorage.app',
  );

}